(******************************************************************************)
(*                                                                            *)
(*                      LINEAR B ADMINISTRATIVE RECORDS                       *)
(*                                                                            *)
(*     Formalizing the Linear B palace archives: tablets, personnel,          *)
(*     commodities, places, counts, and allocation records in                 *)
(*     Mycenaean administrative ontology.                                     *)
(*                                                                            *)
(*     "the prosaic and often trivial details" - Michael Ventris, 1952        *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: March 9, 2026                                                    *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
